// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonNameSpaceGestionCourrier.Data;

#nullable disable

namespace Gestion_courrier_ANDRIANANTENAINA.Migrations
{
    [DbContext(typeof(GestionCourrierDbContext))]
    [Migration("20230529184826_MigrationCourrier")]
    partial class MigrationCourrier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonNameSpaceGestionCourrier.Models.Courrier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateArrivee")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destinataire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expediteur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Urgent_O_N")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courrier");
                });

            modelBuilder.Entity("MonNameSpaceGestionCourrier.Models.MouvementCourrier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Acteur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CourrierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateMouvement")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom_depositaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MouvementCourrier");
                });
#pragma warning restore 612, 618
        }
    }
}
